query getAllGalleries($status: [String]) {
  items {
    gallery(sort: "-date_created", filter: { status: { _in: $status }}) {
      id
      name
      slug
      thumbnail {
        id
        width
        height
      }
    }
  }
}
