query getGalleryBySlug($slug: String) {
  gallery(filter: { slug: { _eq: $slug } }) {
    id
    name
    description
    slug
    thumbnail {
      id
      width
      height
    }
    images(filter: { image: { id: { _nnull: true } } }) {
      image {
        id
        title
        width
        height
      }
    }
    tags
  }
}
