query getAllPosts($status: [String], $limit: Int) {
  posts(
    sort: "-date_created"
    filter: { status: { _in: $status } }
    limit: $limit
  ) {
    id
    title
    subtitle
    date_created
    slug
    thumbnail {
      id
      width
      height
    }
  }
}
