query getPostBySlug($slug: String) {
  items {
    posts(filter: { slug: { _eq: $slug } }) {
      id
      slug
      title
      subtitle
      date_created
      thumbnail {
        id
        width
        height
      }
      body
      tags
    }
  }
}
